
## Turn on lights at sunset
  - alias: light on at sunset
    trigger:
      platform: sun
      event: sunset
      offset: "-00:45:00"
    action:
      - service: scene.turn_on
        entity_id: scene.lights_at_dark

  - alias: light off at sunrise
    trigger:
      platform: sun
      event: sunrise
      offset: "00:20:00"
    action:
      - service: scene.turn_on
        entity_id: scene.lights_at_sunrise
